backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'
show_preview_links: false

media_folder: static/img
public_folder: /img
locale: pl

collections:
  - name: "realizacje"
    label: "Realizacje"
    folder: "src/pages/realizacje"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Galeria zdjęć", name: "imagegalery", widget: list, fields: [{label: Image, name: image, widget: image}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Strony"
    files:
      - file: "src/pages/pl.md"
        label: "Home PL"
        name: "index_pl"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: bg_image, widget: object, fields: [{label: Image, name: image, widget: image}]}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Home Button, name: home_btn, widget: string}
          - {label: Features, name: features, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: string}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}, {label: Services Button, name: services_btn, widget: string}]}
          - {label: Counter, name: counter, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Number, name: number, widget: number,  default: 0, value_type: int}]}
          - {label: "Brands", name: brands, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Images, name: "brands_img", widget: list, fields: [{label: Image, name: image, widget: image}]}]}

      - file: "src/pages/de.md"
        label: "Home DE"
        name: "index_de"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: bg_image, widget: object, fields: [{label: Image, name: image, widget: image}]}
          - {label: Subheading, name: subheading, widget: string}
          - {label: Home Button, name: home_btn, widget: string}
          - {label: Features, name: features, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: string}]}
          - {label: Intro, name: intro, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}, {label: Services Button, name: services_btn, widget: string}]}
          - {label: Counter, name: counter, widget: list, fields: [{label: Title, name: title, widget: string}, {label: Number, name: number, widget: number,  default: 0, value_type: int}]}
          - {label: "Brands", name: brands, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Images, name: "brands_img", widget: list, fields: [{label: Image, name: image, widget: image}]}]}

      - file: "src/pages/about/pl.md"
        label: "O nas PL"
        name: "about_pl"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/about/de.md"
        label: "O nas DE"
        name: "about_de"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/pl.md"
        label: "Usługi PL"
        name: "uslugi_pl"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, summary: '{{fields.title}}', fields: [{label: Image, name: image, widget: image},{label: Title, name: title, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: Services steps, name: services_steps, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Steps, name: steps, widget: list, fields: [{label: Title, name: title, widget: string}, {labet: Description, name: description, widget: string}, {label: Ikon, name: image, widget: image}]}]}
      - file: "src/pages/products/de.md"
        label: "Usługi DE"
        name: "uslugi_de"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, summary: '{{fields.title}}', fields: [{label: Image, name: image, widget: image},{label: Title, name: title, widget: text}, {label: Text, name: text, widget: text}]}]}
          - {label: Services steps, name: services_steps, widget: object, fields: [{label: Title, name: title, widget: string}, {label: Steps, name: steps, widget: list, fields: [{label: Title, name: title, widget: string}, {labet: Description, name: description, widget: string}, {label: Ikon, name: image, widget: image}]}]}
      - file: "src/pages/contact/pl.md"
        label: "Kontakt PL"
        name: "contactpl"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Tytuł, name: title, widget: string}
          - {label: Tytuł formularza, name: subtitle, widget: string}
          - {label: Adres, name: address, widget: object, fields: [{label: Ulica, name: ulica, widget: string}, {label: Miasto, name: miasto, widget: string}, {label: Kod pocztowy, name: kod_pocztowy, widget: string}]}
          - {label: Kontakt, name: contact, widget: object, fields: [{label: Telefon 1, name: telefon1, widget: string}, {label: Telefon 2, name: telefon2, widget: string}, {label: Mail, name: mail, widget: string}]}
          - {label: Godziny otwarcia, name: open_hours, widget: object, fields: [{label: Tytuł, name: title, widget: string}, {label: Dzień pierwszy, name: day_start, widget: string}, {label: Dzień ostatni, name: day_end, widget: string}, {label: Godzina otwarcia, name: hour_start, widget: string}, {label: Godzina zamknięcia, name: hour_end, widget: string}]}
      - file: "src/pages/contact/de.md"
        label: "Kontakt DE"
        name: "contactde"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Tytuł, name: title, widget: string}
          - {label: Tytuł formularza, name: subtitle, widget: string}
          - {label: Adres, name: address, widget: object, fields: [{label: Ulica, name: ulica, widget: string}, {label: Miasto, name: miasto, widget: string}, {label: Kod pocztowy, name: kod_pocztowy, widget: string}]}
          - {label: Kontakt, name: contact, widget: object, fields: [{label: Telefon 1, name: telefon1, widget: string}, {label: Telefon 2, name: telefon2, widget: string}, {label: Mail, name: mail, widget: string}]}
          - {label: Godziny otwarcia, name: open_hours, widget: object, fields: [{label: Tytuł, name: title, widget: string}, {label: Dzień pierwszy, name: day_start, widget: string}, {label: Dzień ostatni, name: day_end, widget: string}, {label: Godzina otwarcia, name: hour_start, widget: string}, {label: Godzina zamknięcia, name: hour_end, widget: string}]}

      